name: Build lectures webpage

on:
  pull_request:
    branches:
      - "main"

  # This workflow can be executed inside another workflow file
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Directory that will be uploaded as an artifact
      PUBLISH_DIR: ./_build/html

    steps:
      - uses: actions/checkout@v3

      - name: Install deps via conda
        uses: ./.github/actions/initialize_conda_env

      - name: cache executed notebooks
        uses: actions/cache@v3
        with:
          path: _build/.jupyter_cache
          key: jupyter-cache-${{ hashFiles('environment.yml') }}

      - name: Install jupyter-book
        run: python3 -m pip install jupyter-book

      - name: Build docs
        run: 	jupyter book build -W .

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ${{ env.PUBLISH_DIR }}
          if-no-files-found: error
  